In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.Using CPU.")

GPU is available!
Using GPU : Tesla T4


**Creating a Tensor**

In [4]:
# using empty
a = torch.empty(2,3)
# empty --memory allocate --shape create value which was already there in memory @ that

In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.8690, 0.0062, 0.4546],
        [0.8978, 0.2380, 0.7146]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.3100, 0.0825, 0.3562],
        [0.1954, 0.4173, 0.7927]])

In [10]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways
# arange
print("suing arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))


suing arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Tensor Shapes**

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    140188079648208,           129697168,                   0],
        [                  0,                   0, 7235419174270214779]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x,dtype=torch.float32)


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**Tensor Data Types**

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


**Mathematical Operations**

1.Scaler Operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [24]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [26]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [31]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [32]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [33]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [35]:
e = torch.randint(size=(2,3), low =0, high = 10, dtype =  torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [36]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [37]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [38]:
# median
torch.median(e)

tensor(0.)

In [39]:
# max & min
torch.max(e)
torch.min(e)

tensor(0.)

In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [42]:
# variance
torch.var(e)

tensor(19.6000)

In [43]:
# argmax
torch.argmax(e)

tensor(5)

In [44]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [45]:
f = torch.randint(size=(2,3),low =0, high = 10)
g = torch.randint(size=(3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [46]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [47]:
vector1 = torch.tensor([1,2,3])
vector2 = torch.tensor([4,5,6])

# dot product
torch.dot(vector1, vector2)

tensor(32)

In [48]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [49]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [50]:
# determinant
torch.det(h)

tensor(-110.)

In [51]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 6. Special functions

In [52]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 8., 3.],
        [6., 1., 5.]])

In [53]:
# log
torch.log(k)

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [54]:
# exp
torch.exp(k)

tensor([[1.0966e+03, 2.9810e+03, 2.0086e+01],
        [4.0343e+02, 2.7183e+00, 1.4841e+02]])

In [55]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.8284, 1.7321],
        [2.4495, 1.0000, 2.2361]])

In [56]:
# softmax
torch.softmax(k, dim=0)

tensor([[7.3106e-01, 9.9909e-01, 1.1920e-01],
        [2.6894e-01, 9.1105e-04, 8.8080e-01]])

In [57]:
# relu
torch.relu(k)

tensor([[7., 8., 3.],
        [6., 1., 5.]])

## Inplace Operations

In [58]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775]])
tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])


In [59]:
m.add_(n)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [60]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [61]:
n

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [62]:
torch.relu(m)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [63]:
m.relu_()

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [64]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

## Copying a Tensor

In [65]:
a = torch.rand(2,3)
a

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [66]:
b = a

In [67]:
b

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [68]:
a[0][0] = 0

In [69]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [70]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [71]:
id(a)

140183533329616

In [72]:
id(b)

140183533329616

In [73]:
b = a.clone()

In [74]:
a

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [75]:
a[0][0] = 10

In [76]:
a

tensor([[10.0000,  0.3451,  0.0453],
        [ 0.9798,  0.5548,  0.6868]])

In [77]:
b

tensor([[0.0000, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [78]:
id(a)

140183533329616

In [79]:
id(b)

140183502417712

## Tensor Operations on GPU

In [80]:
torch.cuda.is_available()

True

In [81]:
device = torch.device('cuda')

In [82]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [83]:
# moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [84]:
b = a.to(device)

In [85]:
b+5

tensor([[5.4920, 5.0748, 5.9605],
        [5.3271, 5.0103, 5.9516]], device='cuda:0')

In [86]:
import time
# Define the size of the matrices
size = 10000 #Large size for performance comparison

#  Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) #Matrix multiplication on CPU
cpu_time = time.time()-start_time

print(f"Time on CPU: {cpu_time: 4f}seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time()-start_time

print(f"Time on GPU: {gpu_time: 4f}seconds")

#Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU:  24.026195seconds
Time on GPU:  0.767461seconds

Speedup (CPU time / GPU time): 31.306096404338913


## Reshaping Tensors

In [87]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
# reshape
a.reshape(2,2,2,2)


tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [90]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
b  = torch.rand(2,3,4)
b

tensor([[[0.6096, 0.5115, 0.0678, 0.5038],
         [0.7779, 0.2659, 0.3932, 0.7483],
         [0.7985, 0.4626, 0.9414, 0.5752]],

        [[0.8881, 0.7989, 0.9514, 0.0141],
         [0.8903, 0.1649, 0.3162, 0.1331],
         [0.6763, 0.4254, 0.2375, 0.5430]]])

In [92]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [94]:
# unsqueeze
# image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [96]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [97]:
import numpy as np


In [98]:
a = torch.tensor([1,2,3])

In [99]:
b = a.numpy()

In [100]:
b

array([1, 2, 3])

In [101]:
type(b)

numpy.ndarray

In [103]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [104]:
torch.from_numpy(c)

tensor([1, 2, 3])